language: php
php:
- 5.3
- 5.4
- 5.5
env:
  global:
    secure: ms6pg+JkqhRPO5TtgpxIMxkBbzUUAuK69c+LHgGYNvVdCg9UbUOhiLeyOBW5uaEnLvMSrpEDDrFhIB2YWu18XCu+YaSXODXsRkiXmNda+OXIcN/7SNoIV3W23y3QAcoGwDFmA7UFLCTs3+bMc/sC1bj6hbh1XSIQZ/R7bfwsWRU=
  cache:
    directories:
      - node_modules
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
before_script:
  - npm install -g grunt-cli
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: 
  - phpunit
  - npm install
  - grunt travis
after_script:
  - grunt phpdocumentor
  - grunt gh-pages:travis
notifications:
  email:
    recipients:
    #- ghost1227@reduxframework.com
    - dovy@reduxframework.com
    on_failure: always
branches:
  except:
    - gh-pages
    - setup